//! Generate TypeScript types + Zod schemas from Rust models.
//!
//! Mirrors the legacy `generate_types` binary that used to live under
//! `crates/remargin/src/bin/`. Moving it here ensures `cargo install
//! remargin` no longer pollutes `~/.cargo/bin/` with a dev-time tool.

use std::fs;
use std::path::Path;

use anyhow::{Context as _, Result};
use remargin_core::activity::{compact_change_row_schema, compact_file_changes_schema};
use remargin_core::config::registry::{participant_status_schema, participant_view_schema};
use remargin_core::document::list_entry_schema;
use remargin_core::on_disk_comment::{on_disk_comment_schema, reaction_entry_on_disk_schema};
use remargin_core::operations::cp::{cp_kind_schema, cp_outcome_schema};
use remargin_core::operations::links::{
    compact_link_row_schema, compact_links_schema, link_schema,
};
use remargin_core::operations::query::{
    compact_comment_row_schema, compact_query_result_schema, expanded_comment_schema,
    query_result_schema,
};
use remargin_core::operations::replace::{replace_file_outcome_schema, replace_report_schema};
use remargin_core::operations::sandbox::{
    sandbox_failure_entry_schema, sandbox_list_entry_schema, sandbox_remove_report_schema,
};
use remargin_core::operations::search::{
    compact_file_matches_schema, compact_match_row_schema, match_location_schema,
    search_hit_location_schema, search_match_schema,
};
use remargin_core::operations::verify::{
    verify_error_kind_schema, verify_failure_payload_schema, verify_failure_row_schema,
};
use remargin_core::parser::{acknowledgment_schema, author_type_schema, comment_schema};
use remargin_core::reactions::reaction_entry_schema;

/// Preamble for `schemas.ts`: the zod import plus the `import type` block
/// naming every generated TS type. Kept here so [`run`] stays under the
/// line cap; the type list order is cosmetic (imports hoist).
const SCHEMAS_HEADER: &str = "// Auto-generated by generate_types. Do not edit.\n\n\
     import { z, type ZodType } from \"zod/v4\";\n\
     import type {\n  \
       AuthorType,\n  \
       Acknowledgment,\n  \
       ReactionEntry,\n  \
       ReactionEntryOnDisk,\n  \
       Comment,\n  \
       OnDiskComment,\n  \
       ListEntry,\n  \
       ExpandedComment,\n  \
       QueryResult,\n  \
       CompactCommentRow,\n  \
       CompactQueryResult,\n  \
       CompactChangeRow,\n  \
       CompactFileChanges,\n  \
       MatchLocation,\n  \
       SearchMatch,\n  \
       SearchHitLocation,\n  \
       CompactMatchRow,\n  \
       CompactFileMatches,\n  \
       ReplaceFileOutcome,\n  \
       ReplaceReport,\n  \
       CpKind,\n  \
       CpOutcome,\n  \
       Link,\n  \
       CompactLinkRow,\n  \
       CompactLinks,\n  \
       SandboxFailureEntry,\n  \
       SandboxListEntry,\n  \
       SandboxRemoveReport,\n  \
       ParticipantStatus,\n  \
       ParticipantView,\n  \
       VerifyErrorKind,\n  \
       VerifyFailureRow,\n  \
       VerifyFailurePayload,\n\
     } from \"./types\";\n\n";

/// Run the type + schema generator, writing into
/// `packages/remargin-obsidian/src/generated/` relative to the repo
/// root. The working directory is expected to be the workspace root —
/// the justfile / pnpm scripts take care of that.
pub fn run() -> Result<()> {
    let out_dir = Path::new("packages/remargin-obsidian/src/generated");
    fs::create_dir_all(out_dir)
        .with_context(|| format!("creating output directory {}", out_dir.display()))?;

    // Order matters: dependencies first.
    let type_defs = [
        author_type_schema::Schema::ts_definition(),
        acknowledgment_schema::Schema::ts_definition(),
        reaction_entry_schema::Schema::ts_definition(),
        reaction_entry_on_disk_schema::Schema::ts_definition(),
        comment_schema::Schema::ts_definition(),
        on_disk_comment_schema::Schema::ts_definition(),
        list_entry_schema::Schema::ts_definition(),
        expanded_comment_schema::Schema::ts_definition(),
        query_result_schema::Schema::ts_definition(),
        compact_comment_row_schema::Schema::ts_definition(),
        compact_query_result_schema::Schema::ts_definition(),
        compact_change_row_schema::Schema::ts_definition(),
        compact_file_changes_schema::Schema::ts_definition(),
        match_location_schema::Schema::ts_definition(),
        search_match_schema::Schema::ts_definition(),
        search_hit_location_schema::Schema::ts_definition(),
        compact_match_row_schema::Schema::ts_definition(),
        compact_file_matches_schema::Schema::ts_definition(),
        replace_file_outcome_schema::Schema::ts_definition(),
        replace_report_schema::Schema::ts_definition(),
        cp_kind_schema::Schema::ts_definition(),
        cp_outcome_schema::Schema::ts_definition(),
        link_schema::Schema::ts_definition(),
        compact_link_row_schema::Schema::ts_definition(),
        compact_links_schema::Schema::ts_definition(),
        sandbox_failure_entry_schema::Schema::ts_definition(),
        sandbox_list_entry_schema::Schema::ts_definition(),
        sandbox_remove_report_schema::Schema::ts_definition(),
        participant_status_schema::Schema::ts_definition(),
        participant_view_schema::Schema::ts_definition(),
        verify_error_kind_schema::Schema::ts_definition(),
        verify_failure_row_schema::Schema::ts_definition(),
        verify_failure_payload_schema::Schema::ts_definition(),
    ];

    let zod_defs = [
        author_type_schema::Schema::zod_schema(),
        acknowledgment_schema::Schema::zod_schema(),
        reaction_entry_schema::Schema::zod_schema(),
        reaction_entry_on_disk_schema::Schema::zod_schema(),
        comment_schema::Schema::zod_schema(),
        on_disk_comment_schema::Schema::zod_schema(),
        list_entry_schema::Schema::zod_schema(),
        expanded_comment_schema::Schema::zod_schema(),
        query_result_schema::Schema::zod_schema(),
        compact_comment_row_schema::Schema::zod_schema(),
        compact_query_result_schema::Schema::zod_schema(),
        compact_change_row_schema::Schema::zod_schema(),
        compact_file_changes_schema::Schema::zod_schema(),
        match_location_schema::Schema::zod_schema(),
        search_match_schema::Schema::zod_schema(),
        search_hit_location_schema::Schema::zod_schema(),
        compact_match_row_schema::Schema::zod_schema(),
        compact_file_matches_schema::Schema::zod_schema(),
        replace_file_outcome_schema::Schema::zod_schema(),
        replace_report_schema::Schema::zod_schema(),
        cp_kind_schema::Schema::zod_schema(),
        cp_outcome_schema::Schema::zod_schema(),
        link_schema::Schema::zod_schema(),
        compact_link_row_schema::Schema::zod_schema(),
        compact_links_schema::Schema::zod_schema(),
        sandbox_failure_entry_schema::Schema::zod_schema(),
        sandbox_list_entry_schema::Schema::zod_schema(),
        sandbox_remove_report_schema::Schema::zod_schema(),
        participant_status_schema::Schema::zod_schema(),
        participant_view_schema::Schema::zod_schema(),
        verify_error_kind_schema::Schema::zod_schema(),
        verify_failure_row_schema::Schema::zod_schema(),
        verify_failure_payload_schema::Schema::zod_schema(),
    ];

    let mut types_content = String::from("// Auto-generated by generate_types. Do not edit.\n\n");
    for def in &type_defs {
        types_content.push_str(def);
        types_content.push('\n');
    }
    let final_types_content = quote_hyphen_keys(&types_content);
    write_file(&out_dir.join("types.ts"), &final_types_content)?;

    let mut schemas_content = String::from(SCHEMAS_HEADER);
    for def in &zod_defs {
        schemas_content.push_str(def);
        schemas_content.push('\n');
    }
    let final_schemas_content = quote_hyphen_keys(&schemas_content);
    write_file(&out_dir.join("schemas.ts"), &final_schemas_content)?;

    let index_content = "// Auto-generated by generate_types. Do not edit.\n\n\
         export * from \"./types\";\n\
         export * from \"./schemas\";\n";
    write_file(&out_dir.join("index.ts"), index_content)?;

    println!("Generated types in {}", out_dir.display());
    Ok(())
}

fn write_file(path: &Path, content: &str) -> Result<()> {
    fs::write(path, content).with_context(|| format!("writing {}", path.display()))?;
    println!("  wrote {}", path.display());
    Ok(())
}

/// Quote any property key that contains a hyphen so the generated TS
/// parses. Tixschema emits `reply-to: string;` verbatim from the serde
/// rename, which is invalid TypeScript / Zod syntax.
fn quote_hyphen_keys(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for line in input.split_inclusive('\n') {
        if let Some(transformed) = quote_hyphen_key_line(line) {
            out.push_str(&transformed);
        } else {
            out.push_str(line);
        }
    }
    out
}

fn quote_hyphen_key_line(line: &str) -> Option<String> {
    let trimmed = line.trim_start();
    let leading_ws_len = line.len() - trimmed.len();
    let colon_pos = trimmed.find(':')?;
    let key = &trimmed[..colon_pos];
    if !key.contains('-') {
        return None;
    }
    if !key
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        return None;
    }
    let mut quoted = String::with_capacity(line.len() + 2);
    quoted.push_str(&line[..leading_ws_len]);
    quoted.push('"');
    quoted.push_str(key);
    quoted.push('"');
    quoted.push_str(&trimmed[colon_pos..]);
    Some(quoted)
}
