//! Generate TypeScript types + Zod schemas from Rust models.
//!
//! Mirrors the legacy `generate_types` binary that used to live under
//! `crates/remargin/src/bin/`. Moving it here ensures `cargo install
//! remargin` no longer pollutes `~/.cargo/bin/` with a dev-time tool
//! (rem-o2p).

use std::fs;
use std::path::Path;

use anyhow::{Context as _, Result};
use remargin_core::document::list_entry_schema;
use remargin_core::operations::query::{expanded_comment_schema, query_result_schema};
use remargin_core::operations::search::{match_location_schema, search_match_schema};
use remargin_core::parser::{acknowledgment_schema, author_type_schema, comment_schema};

/// Run the type + schema generator, writing into
/// `packages/remargin-obsidian/src/generated/` relative to the repo
/// root. The working directory is expected to be the workspace root —
/// the justfile / pnpm scripts take care of that.
pub fn run() -> Result<()> {
    let out_dir = Path::new("packages/remargin-obsidian/src/generated");
    fs::create_dir_all(out_dir)
        .with_context(|| format!("creating output directory {}", out_dir.display()))?;

    // Order matters: dependencies first.
    let type_defs = [
        author_type_schema::Schema::ts_definition(),
        acknowledgment_schema::Schema::ts_definition(),
        comment_schema::Schema::ts_definition(),
        list_entry_schema::Schema::ts_definition(),
        expanded_comment_schema::Schema::ts_definition(),
        query_result_schema::Schema::ts_definition(),
        match_location_schema::Schema::ts_definition(),
        search_match_schema::Schema::ts_definition(),
    ];

    let zod_defs = [
        author_type_schema::Schema::zod_schema(),
        acknowledgment_schema::Schema::zod_schema(),
        comment_schema::Schema::zod_schema(),
        list_entry_schema::Schema::zod_schema(),
        expanded_comment_schema::Schema::zod_schema(),
        query_result_schema::Schema::zod_schema(),
        match_location_schema::Schema::zod_schema(),
        search_match_schema::Schema::zod_schema(),
    ];

    let mut types_content = String::from("// Auto-generated by generate_types. Do not edit.\n\n");
    for def in &type_defs {
        types_content.push_str(def);
        types_content.push('\n');
    }
    write_file(&out_dir.join("types.ts"), &types_content)?;

    let mut schemas_content = String::from(
        "// Auto-generated by generate_types. Do not edit.\n\n\
         import { z, type ZodType } from \"zod/v4\";\n\
         import type {\n  \
           AuthorType,\n  \
           Acknowledgment,\n  \
           Comment,\n  \
           ListEntry,\n  \
           ExpandedComment,\n  \
           QueryResult,\n  \
           MatchLocation,\n  \
           SearchMatch,\n\
         } from \"./types\";\n\n",
    );
    for def in &zod_defs {
        schemas_content.push_str(def);
        schemas_content.push('\n');
    }
    write_file(&out_dir.join("schemas.ts"), &schemas_content)?;

    let index_content = "// Auto-generated by generate_types. Do not edit.\n\n\
         export * from \"./types\";\n\
         export * from \"./schemas\";\n";
    write_file(&out_dir.join("index.ts"), index_content)?;

    println!("Generated types in {}", out_dir.display());
    Ok(())
}

fn write_file(path: &Path, content: &str) -> Result<()> {
    fs::write(path, content).with_context(|| format!("writing {}", path.display()))?;
    println!("  wrote {}", path.display());
    Ok(())
}
