//! Generate TypeScript types + Zod schemas from Rust models.

use std::fs;
use std::path::Path;

use anyhow::{Context as _, Result};
use remargin_core::activity::{compact_change_row_schema, compact_file_changes_schema};
use remargin_core::config::registry::{participant_status_schema, participant_view_schema};
use remargin_core::document::list_entry_schema;
use remargin_core::on_disk_comment::{on_disk_comment_schema, reaction_entry_on_disk_schema};
use remargin_core::operations::cp::{cp_kind_schema, cp_outcome_schema};
use remargin_core::operations::links::{
    compact_link_row_schema, compact_links_schema, link_schema,
};
use remargin_core::operations::query::{
    compact_comment_row_schema, compact_query_result_schema, expanded_comment_schema,
    query_result_schema,
};
use remargin_core::operations::replace::{replace_file_outcome_schema, replace_report_schema};
use remargin_core::operations::sandbox::{
    sandbox_failure_entry_schema, sandbox_list_entry_schema, sandbox_remove_report_schema,
};
use remargin_core::operations::search::{
    compact_file_matches_schema, compact_match_row_schema, match_location_schema,
    search_hit_location_schema, search_match_schema,
};
use remargin_core::operations::verify::{
    verify_error_kind_schema, verify_failure_payload_schema, verify_failure_row_schema,
};
use remargin_core::parser::{acknowledgment_schema, author_type_schema, comment_schema};
use remargin_core::permissions::doctor::{
    doctor_finding_schema, doctor_report_schema, finding_kind_schema, severity_schema,
};
use remargin_core::reactions::reaction_entry_schema;

/// One registered schema module as the pair of renderings it publishes.
macro_rules! registration {
    ($module:ident) => {
        (
            $module::Schema::ts_definition(),
            $module::Schema::zod_schema(),
        )
    };
}

/// Preamble for `schemas.ts`: the zod import and an `import type` of every generated type.
/// `ZodType` is imported unqualified because `model_schema!` spells its annotation that way.
const SCHEMAS_HEADER: &str = "// Auto-generated by generate_types. Do not edit.\n\n\
     import { z, type ZodType } from \"zod/v4\";\n\
     import type {\n  \
       AuthorType,\n  \
       Acknowledgment,\n  \
       ReactionEntry,\n  \
       ReactionEntryOnDisk,\n  \
       Comment,\n  \
       OnDiskComment,\n  \
       ListEntry,\n  \
       ExpandedComment,\n  \
       QueryResult,\n  \
       CompactCommentRow,\n  \
       CompactQueryResult,\n  \
       CompactChangeRow,\n  \
       CompactFileChanges,\n  \
       MatchLocation,\n  \
       SearchMatch,\n  \
       SearchHitLocation,\n  \
       CompactMatchRow,\n  \
       CompactFileMatches,\n  \
       ReplaceFileOutcome,\n  \
       ReplaceReport,\n  \
       CpKind,\n  \
       CpOutcome,\n  \
       Link,\n  \
       CompactLinkRow,\n  \
       CompactLinks,\n  \
       SandboxFailureEntry,\n  \
       SandboxListEntry,\n  \
       SandboxRemoveReport,\n  \
       ParticipantStatus,\n  \
       ParticipantView,\n  \
       VerifyErrorKind,\n  \
       VerifyFailureRow,\n  \
       VerifyFailurePayload,\n  \
       Severity,\n  \
       FindingKind,\n  \
       DoctorFinding,\n  \
       DoctorReport,\n\
     } from \"./types\";\n\n";

/// Run the type + schema generator, writing into
/// `packages/remargin-obsidian/src/generated/` relative to the repo
/// root. The working directory is expected to be the workspace root —
/// the justfile / pnpm scripts take care of that.
pub fn run() -> Result<()> {
    let out_dir = Path::new("packages/remargin-obsidian/src/generated");
    fs::create_dir_all(out_dir)
        .with_context(|| format!("creating output directory {}", out_dir.display()))?;

    // Order matters: dependencies first.
    let registry = [
        registration!(author_type_schema),
        registration!(acknowledgment_schema),
        registration!(reaction_entry_schema),
        registration!(reaction_entry_on_disk_schema),
        registration!(comment_schema),
        registration!(on_disk_comment_schema),
        registration!(list_entry_schema),
        registration!(expanded_comment_schema),
        registration!(query_result_schema),
        registration!(compact_comment_row_schema),
        registration!(compact_query_result_schema),
        registration!(compact_change_row_schema),
        registration!(compact_file_changes_schema),
        registration!(match_location_schema),
        registration!(search_match_schema),
        registration!(search_hit_location_schema),
        registration!(compact_match_row_schema),
        registration!(compact_file_matches_schema),
        registration!(replace_file_outcome_schema),
        registration!(replace_report_schema),
        registration!(cp_kind_schema),
        registration!(cp_outcome_schema),
        registration!(link_schema),
        registration!(compact_link_row_schema),
        registration!(compact_links_schema),
        registration!(sandbox_failure_entry_schema),
        registration!(sandbox_list_entry_schema),
        registration!(sandbox_remove_report_schema),
        registration!(participant_status_schema),
        registration!(participant_view_schema),
        registration!(verify_error_kind_schema),
        registration!(verify_failure_row_schema),
        registration!(verify_failure_payload_schema),
        registration!(severity_schema),
        registration!(finding_kind_schema),
        registration!(doctor_finding_schema),
        registration!(doctor_report_schema),
    ];

    let mut types_content = String::from("// Auto-generated by generate_types. Do not edit.\n\n");
    let mut schemas_content = String::from(SCHEMAS_HEADER);
    for (ts_def, zod_def) in registry {
        types_content.push_str(&ts_def);
        schemas_content.push_str(&zod_def);
        types_content.push('\n');
        schemas_content.push('\n');
    }

    write_file(&out_dir.join("types.ts"), &types_content)?;
    write_file(&out_dir.join("schemas.ts"), &schemas_content)?;

    let index_content = "// Auto-generated by generate_types. Do not edit.\n\n\
         export * from \"./types\";\n\
         export * from \"./schemas\";\n";
    write_file(&out_dir.join("index.ts"), index_content)?;

    println!("Generated types in {}", out_dir.display());
    Ok(())
}

fn write_file(path: &Path, content: &str) -> Result<()> {
    fs::write(path, content).with_context(|| format!("writing {}", path.display()))?;
    println!("  wrote {}", path.display());
    Ok(())
}
